### ISSUE TITLE
issue with fresh install  . angular cli v 6.1.1 

### ISSUE THREAD

**Issue by rahmatputrawiranata** [bknds/ng-pi-admin#1]
**fresh install case**
> Your global Angular CLI version (6.1.1) is greater than your local
> version (1.3.1). The local Angular CLI version is used.
> 
> To disable this warning use "ng config -g cli.warnings.versionMismatch false".
> Cannot read property 'write' of undefined
> TypeError: Cannot read property 'write' of undefined
>     at UI.write (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\ember-cli\lib\ui\index.js:56:23)
>     at UI.writeLine (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\ember-cli\lib\ui\index.js:69:8)
>     at Class.run (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\tasks\serve.js:188:12)
>     at check_port_1.checkPort.then.port (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\commands\serve.js:114:26)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**but when update package.json at @angula/cli : '6.1.1'
got another error** 

> Local workspace file ('angular.json') could not be found.
> Error: Local workspace file ('angular.json') could not be found.
>     at WorkspaceLoader._getProjectWorkspaceFilePath (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\workspace-loader.js:44:19)
>     at WorkspaceLoader.loadWorkspace (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\workspace-loader.js:31:21)
>     at ServeCommand._loadWorkspaceAndArchitect (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\architect-command.js:189:32)
>     at ServeCommand.<anonymous> (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\architect-command.js:55:25)
>     at Generator.next (<anonymous>)
>     at D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\architect-command.js:14:71
>     at new Promise (<anonymous>)
>     at __awaiter (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\architect-command.js:10:12)
>     at ServeCommand.initialize (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\architect-command.js:54:16)
>     at Object.<anonymous> (D:\work\lumen\yunp-brow\ng-pi-admin\node_modules\@angular\cli\models\command-runner.js:101:23)

**Comment by PontesVinicius** [comment]
After updating the local CLI, you need to run the ng update command.
This command will rename the file angular-cli.json to angular.json
