### ISSUE TITLE
Navbar on smartphone

### ISSUE THREAD

**Issue by mistral61** [bknds/ng-pi-admin#3]
Viewed on a smartphone there is no way to access the left lateral menu, clicking the button for hiding/ showing the lateral menu nothing happens.

**Comment by Chekist-mgn** [comment]
Hello! in sidebar.component.scss delete or comment this strings:
@media (max-width:970px) {
     .pages-sider {
         width: 0;
     }
 }

**Comment by mrh-jishan** [comment]
the issue is fixed, maybe they will update in the next release.
