### ISSUE TITLE
How to create nav bar similar to sidebar 

### ISSUE THREAD

**Issue by Bharathsiva** [bknds/ng-pi-admin#5]
Hi,
 Guide me how to create nav bar for this angular application.

**Comment by bknds** [comment]
File path 
ng-pi-admin/src/app/pages/menu.ts

**Comment by Bharathsiva** [comment]
hi @bknds 
This menu.ts is for side nav right.
ng-pi-admin/src/app/pages/pages-top/  in this location we can create navbar right....but i am new this angular. i don't know how to proceed from next

**Comment by bknds** [comment]
You can learn how to create & use angular module & routing file

import { Routes, RouterModule } from '@angular/router';
import { PagesComponent } from './pages.component';
import { LoginComponent } from './login/login.component';
export const childRoutes: Routes = [
    {
        path: 'login',
        component: LoginComponent,
    },
    {
        path: 'pages',
        component: PagesComponent,
        children: [
            { path: '', redirectTo: 'index', pathMatch: 'full' },
            { path: 'index', loadChildren: './index/index.module#IndexModule' },
            { path: 'editor', loadChildren: './editor/editor.module#EditorModule' },
            { path: 'icon', loadChildren: './icon/icon.module#IconModule' },
            { path: 'profile', loadChildren: './profile/profile.module#ProfileModule' },
            { path: 'form', loadChildren: './form/form.module#FormModule' },
            { path: 'charts', loadChildren: './charts/charts.module#ChartsModule' },
            { path: 'ui', loadChildren: './ui/ui.module#UIModule' },
            { path: 'table', loadChildren: './table/table.module#TableModule' },
            { path: 'menu-levels', loadChildren: './menu-levels/menu-levels.module#MenuLevelsModule' },
        ]
    }
];

export const routing = RouterModule.forChild(childRoutes);

**Comment by Bharathsiva** [comment]
hi @bknds  using menu.ts and page-top component, i can create top nav bar but some functionality are not working.hereby i attached my files

[pages-top.zip](https://github.com/bknds/ng-pi-admin/files/2651929/pages-top.zip)

**Comment by bknds** [comment]
Can you describe it in more detail?
